"""The gym_bridge config, merged from independent files: gym base, map, LiDAR, mount. No ROS imports."""
from __future__ import annotations

import copy
import os
import tempfile
from typing import Any

import yaml

MAP_KEYS: tuple[str, ...] = ('map_path', 'sx', 'sy', 'stheta')
LIDAR_KEYS: tuple[str, ...] = ('fov_deg', 'resolution_deg', 'range_min', 'range_max')
MOUNT_KEYS: tuple[str, ...] = ('x', 'y', 'z', 'yaw', 'roll')


def load_yaml(path: str) -> dict[str, Any]:
    with open(path) as yaml_file:
        content = yaml.safe_load(yaml_file)
    if not isinstance(content, dict):
        raise ValueError(f'{path} is not a YAML mapping')
    return content


def _require(values: dict[str, Any], keys: tuple[str, ...], what: str) -> None:
    missing = [key for key in keys if key not in values]
    if missing:
        raise ValueError(f'{what} is missing {", ".join(missing)}')


def load_mount(path: str) -> dict[str, float]:
    """base_link -> laser: x, y, z, yaw, roll."""
    mount = load_yaml(path).get('base_link_to_laser', {})
    _require(mount, MOUNT_KEYS, path)
    return {key: float(mount[key]) for key in MOUNT_KEYS}


def load_lidar(path: str) -> dict[str, Any]:
    """The parameters of a lidar_model parameter file."""
    lidar: dict[str, Any] = load_yaml(path).get('/**', {}).get('ros__parameters', {})
    _require(lidar, LIDAR_KEYS, path)
    return lidar


def build_gym_config(
    base: dict[str, Any], map_config: dict[str, Any], lidar: dict[str, Any], mount: dict[str, float]
) -> dict[str, Any]:
    """Base gym config + the map's values + the gym's own LiDAR, derived from the laser and its mount.

    The gym's LiDAR is not what the stack sees (lidar_model publishes /scan); the gym needs
    it for its wall collision check, so it gets the same geometry and no noise.
    """
    _require(map_config, MAP_KEYS, 'the map file')
    _require(lidar, LIDAR_KEYS, 'the lidar file')
    config = copy.deepcopy(base)
    params: dict[str, Any] = config['bridge']['ros__parameters']
    params.update(map_config)
    half_fov = float(lidar['fov_deg']) / 2.0
    params.update({
        'lidar_enabled': True,
        'lidar_base_link_to_lidar_tf': [mount['x'], mount['y'], mount['yaw']],
        'lidar_noise_std': 0.0,
        'scan_num_beams': round(float(lidar['fov_deg']) / float(lidar['resolution_deg'])) + 1,
        'scan_range_min': float(lidar['range_min']),
        'scan_range_max': float(lidar['range_max']),
        'scan_angle_min': -half_fov,  # degrees
        'scan_angle_max': half_fov,
    })
    return config


def write_gym_config(config: dict[str, Any], name: str) -> str:
    """Write the merged config where the gym launch can read it; returns the path."""
    directory = os.path.join(tempfile.gettempdir(), 'polimi_sim')
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, f'gym_{name}.yaml')
    with open(path, 'w') as config_file:
        config_file.write('# Generated by polimi_sim at launch. Do not edit: edit ros2_ws/config instead.\n')
        yaml.safe_dump(config, config_file, sort_keys=False)
    return path
